# Display information for crate chests holograms
hologram:
  lines:
    - "&eCrate %name%"
    - "&e&lCLICK DERECHO"

# Display information for key items
key:
  name: "&eKey %name%"
  lore:
    - "&7Exchange this key on the spawn!"

# Display information for crate inventories
inventory:
  title: "&eCrate %name%"

command_usage: "&c/%label% %cmd% %args%"

no_console: "&cYou can't use this command from the console!"
no_permission: "&cNot enough permissions!"
no_block: "&cYou aren't aiming at any block!"
no_keys: "&cYou have no keys pending to claim!"

add_location:
  success: "&aYou added a location for the crate &b%name%&a!"
  description: "Adds the given Crate location!"

check:
  success: "&aYou have &b%amount%&a keys to claim!"
  description: "Checks your pending keys!"